service = "go-ApmExam3"

[logconfig]
    logpath = "C:/workspace/logs/go-ApmExam3.log"
    loglevel = "debug"

[databases]
    [databases.postgres]
        server = "local"
        port = "5432"
        enable = true
[servers]
    [servers.api]
        ip = "127.0.0.1"
        port = ":7001"
