service = "go.templete.api"

[logconfig]
    logpath = "/home/logs/go.templete.api.log"
    loglevel = "info"

[databases]
    [databases.postgres]
        server = "localhost"
        port = "5432"
        enable = true
[servers]
    [servers.api]
        ip = "127.0.0.1"
        port = ":7001"

